name: smart_liveliness_detection
description: This package helps you verify that a real person is present in front of the camera, not a photo, video, or mask.
version: 0.2.0
homepage: https://github.com/demola234/smart_liveliness_detection

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.2
  # The default Android implementation from camera_android_camerax doesn't support the required image format.
  camera_android: ^0.10.10+1
  google_mlkit_face_detection: ^0.13.1
  sensors_plus: ^6.1.1

  provider: ^6.1.2
  uuid: ^4.5.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  dartdoc: ^8.1.0
  flutter_test:
    sdk: flutter

platforms:
  ? android
  ? ios

flutter:
  uses-material-design: true
